version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl_v5
    - zerologlint
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: lax
          deny:
            - pkg: io/ioutil
              desc: replaced by io and os packages since Go 1.16
    exhaustruct:
      exclude:
        - ^net/http.Client$
        - ^net/http.Cookie$
        - ^net/http.Request$
        - ^net/http.Response$
        - ^net/http.Server$
        - ^net/http.Transport$
        - .+/cobra.Command$
        - .+openai.ChatCompletionRequest
        - .+openai.ChatCompletionMessage
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
          msg: reasons
        - pattern: ^cmd\.Print.*$
          msg: use ux.Fprint(cmd.OutOrStdout(), msg) instead
    nlreturn:
      block-size: 2
    revive:
      enable-all-rules: false
      rules:
        - name: argument-limit
          arguments:
            - 4
        - name: bare-return
          disabled: false
        - name: blank-imports
          disabled: false
        - name: error-naming
          disabled: false
        - name: error-return
          disabled: false
        - name: error-strings
          disabled: false
        - name: exported
          disabled: false
        - name: increment-decrement
          disabled: false
        - name: indent-error-flow
          disabled: false
        - name: receiver-naming
          disabled: false
        - name: range
          disabled: false
        - name: var-naming
          disabled: false
    staticcheck:
      checks:
        - all
    varnamelen:
      ignore-decls:
        - w http.ResponseWriter
        - r *http.Request
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gochecknoglobals
          - gochecknoinits
        path: cmd
      - linters:
          - gochecknoglobals
        path: internal/build
      - linters:
          - gochecknoglobals
        path: internal/telemetry
      - linters:
          - ireturn
          - wrapcheck
        path: internal/pipeline
      - linters:
          - gochecknoglobals
        path: internal/ux
      - linters:
          - varnamelen
        path: (.+)\.go$
      - linters:
          - ireturn
        path: internal/wizard/.*\.go$
    paths:
      - bin
      - vendor
      - mocks
      - internal/telemetry
      - .codecov.yml
      - .coveralls.yml
      - .git
      - .gitattributes
      - .github
      - .gitignore
      - .gitlab
      - .gitmodules
      - .golangci
      - .golangci.yaml
      - .goreleaser
      - .goreleaser.d
      - .goreleaser.yml
      - .idea
      - .mockery.yaml
      - .travis.yml
      - .vscode
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/intility/indev)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - bin
      - vendor
      - mocks
      - internal/telemetry
      - .codecov.yml
      - .coveralls.yml
      - .git
      - .gitattributes
      - .github
      - .gitignore
      - .gitlab
      - .gitmodules
      - .golangci
      - .golangci.yaml
      - .goreleaser
      - .goreleaser.d
      - .goreleaser.yml
      - .idea
      - .mockery.yaml
      - .travis.yml
      - .vscode
      - third_party$
      - builtin$
      - examples$
