// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/intility/indev/pkg/client"
	mock "github.com/stretchr/testify/mock"
)

// AIAPIKeyClient is an autogenerated mock type for the AIAPIKeyClient type
type AIAPIKeyClient struct {
	mock.Mock
}

type AIAPIKeyClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AIAPIKeyClient) EXPECT() *AIAPIKeyClient_Expecter {
	return &AIAPIKeyClient_Expecter{mock: &_m.Mock}
}

// CreateAIAPIKey provides a mock function with given fields: ctx, deploymentID, request
func (_m *AIAPIKeyClient) CreateAIAPIKey(ctx context.Context, deploymentID string, request client.NewAIAPIKeyRequest) (*client.AIAPIKeyWithSecret, error) {
	ret := _m.Called(ctx, deploymentID, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateAIAPIKey")
	}

	var r0 *client.AIAPIKeyWithSecret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.NewAIAPIKeyRequest) (*client.AIAPIKeyWithSecret, error)); ok {
		return rf(ctx, deploymentID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.NewAIAPIKeyRequest) *client.AIAPIKeyWithSecret); ok {
		r0 = rf(ctx, deploymentID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.AIAPIKeyWithSecret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.NewAIAPIKeyRequest) error); ok {
		r1 = rf(ctx, deploymentID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AIAPIKeyClient_CreateAIAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAIAPIKey'
type AIAPIKeyClient_CreateAIAPIKey_Call struct {
	*mock.Call
}

// CreateAIAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID string
//   - request client.NewAIAPIKeyRequest
func (_e *AIAPIKeyClient_Expecter) CreateAIAPIKey(ctx interface{}, deploymentID interface{}, request interface{}) *AIAPIKeyClient_CreateAIAPIKey_Call {
	return &AIAPIKeyClient_CreateAIAPIKey_Call{Call: _e.mock.On("CreateAIAPIKey", ctx, deploymentID, request)}
}

func (_c *AIAPIKeyClient_CreateAIAPIKey_Call) Run(run func(ctx context.Context, deploymentID string, request client.NewAIAPIKeyRequest)) *AIAPIKeyClient_CreateAIAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(client.NewAIAPIKeyRequest))
	})
	return _c
}

func (_c *AIAPIKeyClient_CreateAIAPIKey_Call) Return(_a0 *client.AIAPIKeyWithSecret, _a1 error) *AIAPIKeyClient_CreateAIAPIKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AIAPIKeyClient_CreateAIAPIKey_Call) RunAndReturn(run func(context.Context, string, client.NewAIAPIKeyRequest) (*client.AIAPIKeyWithSecret, error)) *AIAPIKeyClient_CreateAIAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAIAPIKey provides a mock function with given fields: ctx, deploymentID, keyID
func (_m *AIAPIKeyClient) DeleteAIAPIKey(ctx context.Context, deploymentID string, keyID string) error {
	ret := _m.Called(ctx, deploymentID, keyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAIAPIKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, deploymentID, keyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AIAPIKeyClient_DeleteAIAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAIAPIKey'
type AIAPIKeyClient_DeleteAIAPIKey_Call struct {
	*mock.Call
}

// DeleteAIAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID string
//   - keyID string
func (_e *AIAPIKeyClient_Expecter) DeleteAIAPIKey(ctx interface{}, deploymentID interface{}, keyID interface{}) *AIAPIKeyClient_DeleteAIAPIKey_Call {
	return &AIAPIKeyClient_DeleteAIAPIKey_Call{Call: _e.mock.On("DeleteAIAPIKey", ctx, deploymentID, keyID)}
}

func (_c *AIAPIKeyClient_DeleteAIAPIKey_Call) Run(run func(ctx context.Context, deploymentID string, keyID string)) *AIAPIKeyClient_DeleteAIAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AIAPIKeyClient_DeleteAIAPIKey_Call) Return(_a0 error) *AIAPIKeyClient_DeleteAIAPIKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AIAPIKeyClient_DeleteAIAPIKey_Call) RunAndReturn(run func(context.Context, string, string) error) *AIAPIKeyClient_DeleteAIAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetAIAPIKey provides a mock function with given fields: ctx, deploymentID, name
func (_m *AIAPIKeyClient) GetAIAPIKey(ctx context.Context, deploymentID string, name string) (*client.AIAPIKey, error) {
	ret := _m.Called(ctx, deploymentID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetAIAPIKey")
	}

	var r0 *client.AIAPIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*client.AIAPIKey, error)); ok {
		return rf(ctx, deploymentID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *client.AIAPIKey); ok {
		r0 = rf(ctx, deploymentID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.AIAPIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, deploymentID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AIAPIKeyClient_GetAIAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAIAPIKey'
type AIAPIKeyClient_GetAIAPIKey_Call struct {
	*mock.Call
}

// GetAIAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID string
//   - name string
func (_e *AIAPIKeyClient_Expecter) GetAIAPIKey(ctx interface{}, deploymentID interface{}, name interface{}) *AIAPIKeyClient_GetAIAPIKey_Call {
	return &AIAPIKeyClient_GetAIAPIKey_Call{Call: _e.mock.On("GetAIAPIKey", ctx, deploymentID, name)}
}

func (_c *AIAPIKeyClient_GetAIAPIKey_Call) Run(run func(ctx context.Context, deploymentID string, name string)) *AIAPIKeyClient_GetAIAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AIAPIKeyClient_GetAIAPIKey_Call) Return(_a0 *client.AIAPIKey, _a1 error) *AIAPIKeyClient_GetAIAPIKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AIAPIKeyClient_GetAIAPIKey_Call) RunAndReturn(run func(context.Context, string, string) (*client.AIAPIKey, error)) *AIAPIKeyClient_GetAIAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// ListAIAPIKeys provides a mock function with given fields: ctx, deploymentID
func (_m *AIAPIKeyClient) ListAIAPIKeys(ctx context.Context, deploymentID string) ([]client.AIAPIKey, error) {
	ret := _m.Called(ctx, deploymentID)

	if len(ret) == 0 {
		panic("no return value specified for ListAIAPIKeys")
	}

	var r0 []client.AIAPIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]client.AIAPIKey, error)); ok {
		return rf(ctx, deploymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []client.AIAPIKey); ok {
		r0 = rf(ctx, deploymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.AIAPIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, deploymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AIAPIKeyClient_ListAIAPIKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAIAPIKeys'
type AIAPIKeyClient_ListAIAPIKeys_Call struct {
	*mock.Call
}

// ListAIAPIKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID string
func (_e *AIAPIKeyClient_Expecter) ListAIAPIKeys(ctx interface{}, deploymentID interface{}) *AIAPIKeyClient_ListAIAPIKeys_Call {
	return &AIAPIKeyClient_ListAIAPIKeys_Call{Call: _e.mock.On("ListAIAPIKeys", ctx, deploymentID)}
}

func (_c *AIAPIKeyClient_ListAIAPIKeys_Call) Run(run func(ctx context.Context, deploymentID string)) *AIAPIKeyClient_ListAIAPIKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AIAPIKeyClient_ListAIAPIKeys_Call) Return(_a0 []client.AIAPIKey, _a1 error) *AIAPIKeyClient_ListAIAPIKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AIAPIKeyClient_ListAIAPIKeys_Call) RunAndReturn(run func(context.Context, string) ([]client.AIAPIKey, error)) *AIAPIKeyClient_ListAIAPIKeys_Call {
	_c.Call.Return(run)
	return _c
}

// NewAIAPIKeyClient creates a new instance of AIAPIKeyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAIAPIKeyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AIAPIKeyClient {
	mock := &AIAPIKeyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
