// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/intility/indev/pkg/client"
	mock "github.com/stretchr/testify/mock"
)

// AIClient is an autogenerated mock type for the AIClient type
type AIClient struct {
	mock.Mock
}

type AIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AIClient) EXPECT() *AIClient_Expecter {
	return &AIClient_Expecter{mock: &_m.Mock}
}

// CreateAIDeployment provides a mock function with given fields: ctx, request
func (_m *AIClient) CreateAIDeployment(ctx context.Context, request client.NewAIDeploymentRequest) (*client.AIDeployment, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateAIDeployment")
	}

	var r0 *client.AIDeployment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.NewAIDeploymentRequest) (*client.AIDeployment, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.NewAIDeploymentRequest) *client.AIDeployment); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.AIDeployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.NewAIDeploymentRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AIClient_CreateAIDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAIDeployment'
type AIClient_CreateAIDeployment_Call struct {
	*mock.Call
}

// CreateAIDeployment is a helper method to define mock.On call
//   - ctx context.Context
//   - request client.NewAIDeploymentRequest
func (_e *AIClient_Expecter) CreateAIDeployment(ctx interface{}, request interface{}) *AIClient_CreateAIDeployment_Call {
	return &AIClient_CreateAIDeployment_Call{Call: _e.mock.On("CreateAIDeployment", ctx, request)}
}

func (_c *AIClient_CreateAIDeployment_Call) Run(run func(ctx context.Context, request client.NewAIDeploymentRequest)) *AIClient_CreateAIDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.NewAIDeploymentRequest))
	})
	return _c
}

func (_c *AIClient_CreateAIDeployment_Call) Return(_a0 *client.AIDeployment, _a1 error) *AIClient_CreateAIDeployment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AIClient_CreateAIDeployment_Call) RunAndReturn(run func(context.Context, client.NewAIDeploymentRequest) (*client.AIDeployment, error)) *AIClient_CreateAIDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAIDeployment provides a mock function with given fields: ctx, id
func (_m *AIClient) DeleteAIDeployment(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAIDeployment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AIClient_DeleteAIDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAIDeployment'
type AIClient_DeleteAIDeployment_Call struct {
	*mock.Call
}

// DeleteAIDeployment is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *AIClient_Expecter) DeleteAIDeployment(ctx interface{}, id interface{}) *AIClient_DeleteAIDeployment_Call {
	return &AIClient_DeleteAIDeployment_Call{Call: _e.mock.On("DeleteAIDeployment", ctx, id)}
}

func (_c *AIClient_DeleteAIDeployment_Call) Run(run func(ctx context.Context, id string)) *AIClient_DeleteAIDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AIClient_DeleteAIDeployment_Call) Return(_a0 error) *AIClient_DeleteAIDeployment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AIClient_DeleteAIDeployment_Call) RunAndReturn(run func(context.Context, string) error) *AIClient_DeleteAIDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// GetAIDeployment provides a mock function with given fields: ctx, name
func (_m *AIClient) GetAIDeployment(ctx context.Context, name string) (*client.AIDeployment, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetAIDeployment")
	}

	var r0 *client.AIDeployment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.AIDeployment, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.AIDeployment); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.AIDeployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AIClient_GetAIDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAIDeployment'
type AIClient_GetAIDeployment_Call struct {
	*mock.Call
}

// GetAIDeployment is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *AIClient_Expecter) GetAIDeployment(ctx interface{}, name interface{}) *AIClient_GetAIDeployment_Call {
	return &AIClient_GetAIDeployment_Call{Call: _e.mock.On("GetAIDeployment", ctx, name)}
}

func (_c *AIClient_GetAIDeployment_Call) Run(run func(ctx context.Context, name string)) *AIClient_GetAIDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AIClient_GetAIDeployment_Call) Return(_a0 *client.AIDeployment, _a1 error) *AIClient_GetAIDeployment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AIClient_GetAIDeployment_Call) RunAndReturn(run func(context.Context, string) (*client.AIDeployment, error)) *AIClient_GetAIDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// ListAIDeployments provides a mock function with given fields: ctx
func (_m *AIClient) ListAIDeployments(ctx context.Context) ([]client.AIDeployment, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAIDeployments")
	}

	var r0 []client.AIDeployment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.AIDeployment, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.AIDeployment); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.AIDeployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AIClient_ListAIDeployments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAIDeployments'
type AIClient_ListAIDeployments_Call struct {
	*mock.Call
}

// ListAIDeployments is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AIClient_Expecter) ListAIDeployments(ctx interface{}) *AIClient_ListAIDeployments_Call {
	return &AIClient_ListAIDeployments_Call{Call: _e.mock.On("ListAIDeployments", ctx)}
}

func (_c *AIClient_ListAIDeployments_Call) Run(run func(ctx context.Context)) *AIClient_ListAIDeployments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AIClient_ListAIDeployments_Call) Return(_a0 []client.AIDeployment, _a1 error) *AIClient_ListAIDeployments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AIClient_ListAIDeployments_Call) RunAndReturn(run func(context.Context) ([]client.AIDeployment, error)) *AIClient_ListAIDeployments_Call {
	_c.Call.Return(run)
	return _c
}

// ListAIModels provides a mock function with given fields: ctx
func (_m *AIClient) ListAIModels(ctx context.Context) ([]client.AIModel, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAIModels")
	}

	var r0 []client.AIModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.AIModel, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.AIModel); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.AIModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AIClient_ListAIModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAIModels'
type AIClient_ListAIModels_Call struct {
	*mock.Call
}

// ListAIModels is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AIClient_Expecter) ListAIModels(ctx interface{}) *AIClient_ListAIModels_Call {
	return &AIClient_ListAIModels_Call{Call: _e.mock.On("ListAIModels", ctx)}
}

func (_c *AIClient_ListAIModels_Call) Run(run func(ctx context.Context)) *AIClient_ListAIModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AIClient_ListAIModels_Call) Return(_a0 []client.AIModel, _a1 error) *AIClient_ListAIModels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AIClient_ListAIModels_Call) RunAndReturn(run func(context.Context) ([]client.AIModel, error)) *AIClient_ListAIModels_Call {
	_c.Call.Return(run)
	return _c
}

// NewAIClient creates a new instance of AIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AIClient {
	mock := &AIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
