// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/intility/indev/pkg/client"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// AddClusterMember provides a mock function with given fields: ctx, clusterID, request
func (_m *Client) AddClusterMember(ctx context.Context, clusterID string, request []client.AddClusterMemberRequest) error {
	ret := _m.Called(ctx, clusterID, request)

	if len(ret) == 0 {
		panic("no return value specified for AddClusterMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []client.AddClusterMemberRequest) error); ok {
		r0 = rf(ctx, clusterID, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_AddClusterMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddClusterMember'
type Client_AddClusterMember_Call struct {
	*mock.Call
}

// AddClusterMember is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
//   - request []client.AddClusterMemberRequest
func (_e *Client_Expecter) AddClusterMember(ctx interface{}, clusterID interface{}, request interface{}) *Client_AddClusterMember_Call {
	return &Client_AddClusterMember_Call{Call: _e.mock.On("AddClusterMember", ctx, clusterID, request)}
}

func (_c *Client_AddClusterMember_Call) Run(run func(ctx context.Context, clusterID string, request []client.AddClusterMemberRequest)) *Client_AddClusterMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]client.AddClusterMemberRequest))
	})
	return _c
}

func (_c *Client_AddClusterMember_Call) Return(_a0 error) *Client_AddClusterMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_AddClusterMember_Call) RunAndReturn(run func(context.Context, string, []client.AddClusterMemberRequest) error) *Client_AddClusterMember_Call {
	_c.Call.Return(run)
	return _c
}

// AddTeamMember provides a mock function with given fields: ctx, teamID, request
func (_m *Client) AddTeamMember(ctx context.Context, teamID string, request []client.AddTeamMemberRequest) error {
	ret := _m.Called(ctx, teamID, request)

	if len(ret) == 0 {
		panic("no return value specified for AddTeamMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []client.AddTeamMemberRequest) error); ok {
		r0 = rf(ctx, teamID, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_AddTeamMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTeamMember'
type Client_AddTeamMember_Call struct {
	*mock.Call
}

// AddTeamMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - request []client.AddTeamMemberRequest
func (_e *Client_Expecter) AddTeamMember(ctx interface{}, teamID interface{}, request interface{}) *Client_AddTeamMember_Call {
	return &Client_AddTeamMember_Call{Call: _e.mock.On("AddTeamMember", ctx, teamID, request)}
}

func (_c *Client_AddTeamMember_Call) Run(run func(ctx context.Context, teamID string, request []client.AddTeamMemberRequest)) *Client_AddTeamMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]client.AddTeamMemberRequest))
	})
	return _c
}

func (_c *Client_AddTeamMember_Call) Return(_a0 error) *Client_AddTeamMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_AddTeamMember_Call) RunAndReturn(run func(context.Context, string, []client.AddTeamMemberRequest) error) *Client_AddTeamMember_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAIAPIKey provides a mock function with given fields: ctx, deploymentID, request
func (_m *Client) CreateAIAPIKey(ctx context.Context, deploymentID string, request client.NewAIAPIKeyRequest) (*client.AIAPIKeyWithSecret, error) {
	ret := _m.Called(ctx, deploymentID, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateAIAPIKey")
	}

	var r0 *client.AIAPIKeyWithSecret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.NewAIAPIKeyRequest) (*client.AIAPIKeyWithSecret, error)); ok {
		return rf(ctx, deploymentID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.NewAIAPIKeyRequest) *client.AIAPIKeyWithSecret); ok {
		r0 = rf(ctx, deploymentID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.AIAPIKeyWithSecret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.NewAIAPIKeyRequest) error); ok {
		r1 = rf(ctx, deploymentID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_CreateAIAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAIAPIKey'
type Client_CreateAIAPIKey_Call struct {
	*mock.Call
}

// CreateAIAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID string
//   - request client.NewAIAPIKeyRequest
func (_e *Client_Expecter) CreateAIAPIKey(ctx interface{}, deploymentID interface{}, request interface{}) *Client_CreateAIAPIKey_Call {
	return &Client_CreateAIAPIKey_Call{Call: _e.mock.On("CreateAIAPIKey", ctx, deploymentID, request)}
}

func (_c *Client_CreateAIAPIKey_Call) Run(run func(ctx context.Context, deploymentID string, request client.NewAIAPIKeyRequest)) *Client_CreateAIAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(client.NewAIAPIKeyRequest))
	})
	return _c
}

func (_c *Client_CreateAIAPIKey_Call) Return(_a0 *client.AIAPIKeyWithSecret, _a1 error) *Client_CreateAIAPIKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_CreateAIAPIKey_Call) RunAndReturn(run func(context.Context, string, client.NewAIAPIKeyRequest) (*client.AIAPIKeyWithSecret, error)) *Client_CreateAIAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAIDeployment provides a mock function with given fields: ctx, request
func (_m *Client) CreateAIDeployment(ctx context.Context, request client.NewAIDeploymentRequest) (*client.AIDeployment, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateAIDeployment")
	}

	var r0 *client.AIDeployment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.NewAIDeploymentRequest) (*client.AIDeployment, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.NewAIDeploymentRequest) *client.AIDeployment); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.AIDeployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.NewAIDeploymentRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_CreateAIDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAIDeployment'
type Client_CreateAIDeployment_Call struct {
	*mock.Call
}

// CreateAIDeployment is a helper method to define mock.On call
//   - ctx context.Context
//   - request client.NewAIDeploymentRequest
func (_e *Client_Expecter) CreateAIDeployment(ctx interface{}, request interface{}) *Client_CreateAIDeployment_Call {
	return &Client_CreateAIDeployment_Call{Call: _e.mock.On("CreateAIDeployment", ctx, request)}
}

func (_c *Client_CreateAIDeployment_Call) Run(run func(ctx context.Context, request client.NewAIDeploymentRequest)) *Client_CreateAIDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.NewAIDeploymentRequest))
	})
	return _c
}

func (_c *Client_CreateAIDeployment_Call) Return(_a0 *client.AIDeployment, _a1 error) *Client_CreateAIDeployment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_CreateAIDeployment_Call) RunAndReturn(run func(context.Context, client.NewAIDeploymentRequest) (*client.AIDeployment, error)) *Client_CreateAIDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCluster provides a mock function with given fields: ctx, request
func (_m *Client) CreateCluster(ctx context.Context, request client.NewClusterRequest) (*client.Cluster, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateCluster")
	}

	var r0 *client.Cluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.NewClusterRequest) (*client.Cluster, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.NewClusterRequest) *client.Cluster); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Cluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.NewClusterRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_CreateCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCluster'
type Client_CreateCluster_Call struct {
	*mock.Call
}

// CreateCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - request client.NewClusterRequest
func (_e *Client_Expecter) CreateCluster(ctx interface{}, request interface{}) *Client_CreateCluster_Call {
	return &Client_CreateCluster_Call{Call: _e.mock.On("CreateCluster", ctx, request)}
}

func (_c *Client_CreateCluster_Call) Run(run func(ctx context.Context, request client.NewClusterRequest)) *Client_CreateCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.NewClusterRequest))
	})
	return _c
}

func (_c *Client_CreateCluster_Call) Return(_a0 *client.Cluster, _a1 error) *Client_CreateCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_CreateCluster_Call) RunAndReturn(run func(context.Context, client.NewClusterRequest) (*client.Cluster, error)) *Client_CreateCluster_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTeam provides a mock function with given fields: ctx, request
func (_m *Client) CreateTeam(ctx context.Context, request client.NewTeamRequest) (*client.Team, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 *client.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.NewTeamRequest) (*client.Team, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.NewTeamRequest) *client.Team); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.NewTeamRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type Client_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - request client.NewTeamRequest
func (_e *Client_Expecter) CreateTeam(ctx interface{}, request interface{}) *Client_CreateTeam_Call {
	return &Client_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, request)}
}

func (_c *Client_CreateTeam_Call) Run(run func(ctx context.Context, request client.NewTeamRequest)) *Client_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.NewTeamRequest))
	})
	return _c
}

func (_c *Client_CreateTeam_Call) Return(_a0 *client.Team, _a1 error) *Client_CreateTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_CreateTeam_Call) RunAndReturn(run func(context.Context, client.NewTeamRequest) (*client.Team, error)) *Client_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAIAPIKey provides a mock function with given fields: ctx, deploymentID, keyID
func (_m *Client) DeleteAIAPIKey(ctx context.Context, deploymentID string, keyID string) error {
	ret := _m.Called(ctx, deploymentID, keyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAIAPIKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, deploymentID, keyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_DeleteAIAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAIAPIKey'
type Client_DeleteAIAPIKey_Call struct {
	*mock.Call
}

// DeleteAIAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID string
//   - keyID string
func (_e *Client_Expecter) DeleteAIAPIKey(ctx interface{}, deploymentID interface{}, keyID interface{}) *Client_DeleteAIAPIKey_Call {
	return &Client_DeleteAIAPIKey_Call{Call: _e.mock.On("DeleteAIAPIKey", ctx, deploymentID, keyID)}
}

func (_c *Client_DeleteAIAPIKey_Call) Run(run func(ctx context.Context, deploymentID string, keyID string)) *Client_DeleteAIAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Client_DeleteAIAPIKey_Call) Return(_a0 error) *Client_DeleteAIAPIKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_DeleteAIAPIKey_Call) RunAndReturn(run func(context.Context, string, string) error) *Client_DeleteAIAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAIDeployment provides a mock function with given fields: ctx, id
func (_m *Client) DeleteAIDeployment(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAIDeployment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_DeleteAIDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAIDeployment'
type Client_DeleteAIDeployment_Call struct {
	*mock.Call
}

// DeleteAIDeployment is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Client_Expecter) DeleteAIDeployment(ctx interface{}, id interface{}) *Client_DeleteAIDeployment_Call {
	return &Client_DeleteAIDeployment_Call{Call: _e.mock.On("DeleteAIDeployment", ctx, id)}
}

func (_c *Client_DeleteAIDeployment_Call) Run(run func(ctx context.Context, id string)) *Client_DeleteAIDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_DeleteAIDeployment_Call) Return(_a0 error) *Client_DeleteAIDeployment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_DeleteAIDeployment_Call) RunAndReturn(run func(context.Context, string) error) *Client_DeleteAIDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCluster provides a mock function with given fields: ctx, name
func (_m *Client) DeleteCluster(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_DeleteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCluster'
type Client_DeleteCluster_Call struct {
	*mock.Call
}

// DeleteCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Client_Expecter) DeleteCluster(ctx interface{}, name interface{}) *Client_DeleteCluster_Call {
	return &Client_DeleteCluster_Call{Call: _e.mock.On("DeleteCluster", ctx, name)}
}

func (_c *Client_DeleteCluster_Call) Run(run func(ctx context.Context, name string)) *Client_DeleteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_DeleteCluster_Call) Return(_a0 error) *Client_DeleteCluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_DeleteCluster_Call) RunAndReturn(run func(context.Context, string) error) *Client_DeleteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTeam provides a mock function with given fields: ctx, request
func (_m *Client) DeleteTeam(ctx context.Context, request client.DeleteTeamRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.DeleteTeamRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_DeleteTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTeam'
type Client_DeleteTeam_Call struct {
	*mock.Call
}

// DeleteTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - request client.DeleteTeamRequest
func (_e *Client_Expecter) DeleteTeam(ctx interface{}, request interface{}) *Client_DeleteTeam_Call {
	return &Client_DeleteTeam_Call{Call: _e.mock.On("DeleteTeam", ctx, request)}
}

func (_c *Client_DeleteTeam_Call) Run(run func(ctx context.Context, request client.DeleteTeamRequest)) *Client_DeleteTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.DeleteTeamRequest))
	})
	return _c
}

func (_c *Client_DeleteTeam_Call) Return(_a0 error) *Client_DeleteTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_DeleteTeam_Call) RunAndReturn(run func(context.Context, client.DeleteTeamRequest) error) *Client_DeleteTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetAIAPIKey provides a mock function with given fields: ctx, deploymentID, name
func (_m *Client) GetAIAPIKey(ctx context.Context, deploymentID string, name string) (*client.AIAPIKey, error) {
	ret := _m.Called(ctx, deploymentID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetAIAPIKey")
	}

	var r0 *client.AIAPIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*client.AIAPIKey, error)); ok {
		return rf(ctx, deploymentID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *client.AIAPIKey); ok {
		r0 = rf(ctx, deploymentID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.AIAPIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, deploymentID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetAIAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAIAPIKey'
type Client_GetAIAPIKey_Call struct {
	*mock.Call
}

// GetAIAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID string
//   - name string
func (_e *Client_Expecter) GetAIAPIKey(ctx interface{}, deploymentID interface{}, name interface{}) *Client_GetAIAPIKey_Call {
	return &Client_GetAIAPIKey_Call{Call: _e.mock.On("GetAIAPIKey", ctx, deploymentID, name)}
}

func (_c *Client_GetAIAPIKey_Call) Run(run func(ctx context.Context, deploymentID string, name string)) *Client_GetAIAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Client_GetAIAPIKey_Call) Return(_a0 *client.AIAPIKey, _a1 error) *Client_GetAIAPIKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetAIAPIKey_Call) RunAndReturn(run func(context.Context, string, string) (*client.AIAPIKey, error)) *Client_GetAIAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetAIDeployment provides a mock function with given fields: ctx, name
func (_m *Client) GetAIDeployment(ctx context.Context, name string) (*client.AIDeployment, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetAIDeployment")
	}

	var r0 *client.AIDeployment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.AIDeployment, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.AIDeployment); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.AIDeployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetAIDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAIDeployment'
type Client_GetAIDeployment_Call struct {
	*mock.Call
}

// GetAIDeployment is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Client_Expecter) GetAIDeployment(ctx interface{}, name interface{}) *Client_GetAIDeployment_Call {
	return &Client_GetAIDeployment_Call{Call: _e.mock.On("GetAIDeployment", ctx, name)}
}

func (_c *Client_GetAIDeployment_Call) Run(run func(ctx context.Context, name string)) *Client_GetAIDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetAIDeployment_Call) Return(_a0 *client.AIDeployment, _a1 error) *Client_GetAIDeployment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetAIDeployment_Call) RunAndReturn(run func(context.Context, string) (*client.AIDeployment, error)) *Client_GetAIDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// GetCluster provides a mock function with given fields: ctx, name
func (_m *Client) GetCluster(ctx context.Context, name string) (*client.Cluster, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetCluster")
	}

	var r0 *client.Cluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.Cluster, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.Cluster); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Cluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCluster'
type Client_GetCluster_Call struct {
	*mock.Call
}

// GetCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Client_Expecter) GetCluster(ctx interface{}, name interface{}) *Client_GetCluster_Call {
	return &Client_GetCluster_Call{Call: _e.mock.On("GetCluster", ctx, name)}
}

func (_c *Client_GetCluster_Call) Run(run func(ctx context.Context, name string)) *Client_GetCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetCluster_Call) Return(_a0 *client.Cluster, _a1 error) *Client_GetCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetCluster_Call) RunAndReturn(run func(context.Context, string) (*client.Cluster, error)) *Client_GetCluster_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterMembers provides a mock function with given fields: ctx, clusterID
func (_m *Client) GetClusterMembers(ctx context.Context, clusterID string) ([]client.ClusterMember, error) {
	ret := _m.Called(ctx, clusterID)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterMembers")
	}

	var r0 []client.ClusterMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]client.ClusterMember, error)); ok {
		return rf(ctx, clusterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []client.ClusterMember); ok {
		r0 = rf(ctx, clusterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.ClusterMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetClusterMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterMembers'
type Client_GetClusterMembers_Call struct {
	*mock.Call
}

// GetClusterMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
func (_e *Client_Expecter) GetClusterMembers(ctx interface{}, clusterID interface{}) *Client_GetClusterMembers_Call {
	return &Client_GetClusterMembers_Call{Call: _e.mock.On("GetClusterMembers", ctx, clusterID)}
}

func (_c *Client_GetClusterMembers_Call) Run(run func(ctx context.Context, clusterID string)) *Client_GetClusterMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetClusterMembers_Call) Return(_a0 []client.ClusterMember, _a1 error) *Client_GetClusterMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetClusterMembers_Call) RunAndReturn(run func(context.Context, string) ([]client.ClusterMember, error)) *Client_GetClusterMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterStatus provides a mock function with given fields: ctx, clusterID
func (_m *Client) GetClusterStatus(ctx context.Context, clusterID string) (*client.Cluster, error) {
	ret := _m.Called(ctx, clusterID)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterStatus")
	}

	var r0 *client.Cluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.Cluster, error)); ok {
		return rf(ctx, clusterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.Cluster); ok {
		r0 = rf(ctx, clusterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Cluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetClusterStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterStatus'
type Client_GetClusterStatus_Call struct {
	*mock.Call
}

// GetClusterStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
func (_e *Client_Expecter) GetClusterStatus(ctx interface{}, clusterID interface{}) *Client_GetClusterStatus_Call {
	return &Client_GetClusterStatus_Call{Call: _e.mock.On("GetClusterStatus", ctx, clusterID)}
}

func (_c *Client_GetClusterStatus_Call) Run(run func(ctx context.Context, clusterID string)) *Client_GetClusterStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetClusterStatus_Call) Return(_a0 *client.Cluster, _a1 error) *Client_GetClusterStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetClusterStatus_Call) RunAndReturn(run func(context.Context, string) (*client.Cluster, error)) *Client_GetClusterStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetMe provides a mock function with given fields: ctx
func (_m *Client) GetMe(ctx context.Context) (client.Me, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 client.Me
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (client.Me, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) client.Me); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(client.Me)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type Client_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Client_Expecter) GetMe(ctx interface{}) *Client_GetMe_Call {
	return &Client_GetMe_Call{Call: _e.mock.On("GetMe", ctx)}
}

func (_c *Client_GetMe_Call) Run(run func(ctx context.Context)) *Client_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Client_GetMe_Call) Return(_a0 client.Me, _a1 error) *Client_GetMe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetMe_Call) RunAndReturn(run func(context.Context) (client.Me, error)) *Client_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function with given fields: ctx, name
func (_m *Client) GetTeam(ctx context.Context, name string) (*client.Team, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *client.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.Team, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.Team); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type Client_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Client_Expecter) GetTeam(ctx interface{}, name interface{}) *Client_GetTeam_Call {
	return &Client_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, name)}
}

func (_c *Client_GetTeam_Call) Run(run func(ctx context.Context, name string)) *Client_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetTeam_Call) Return(_a0 *client.Team, _a1 error) *Client_GetTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetTeam_Call) RunAndReturn(run func(context.Context, string) (*client.Team, error)) *Client_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamMembers provides a mock function with given fields: ctx, teamID
func (_m *Client) GetTeamMembers(ctx context.Context, teamID string) ([]client.TeamMember, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamMembers")
	}

	var r0 []client.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]client.TeamMember, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []client.TeamMember); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetTeamMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamMembers'
type Client_GetTeamMembers_Call struct {
	*mock.Call
}

// GetTeamMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *Client_Expecter) GetTeamMembers(ctx interface{}, teamID interface{}) *Client_GetTeamMembers_Call {
	return &Client_GetTeamMembers_Call{Call: _e.mock.On("GetTeamMembers", ctx, teamID)}
}

func (_c *Client_GetTeamMembers_Call) Run(run func(ctx context.Context, teamID string)) *Client_GetTeamMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetTeamMembers_Call) Return(_a0 []client.TeamMember, _a1 error) *Client_GetTeamMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetTeamMembers_Call) RunAndReturn(run func(context.Context, string) ([]client.TeamMember, error)) *Client_GetTeamMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, upn
func (_m *Client) GetUser(ctx context.Context, upn string) (*client.User, error) {
	ret := _m.Called(ctx, upn)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *client.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.User, error)); ok {
		return rf(ctx, upn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.User); ok {
		r0 = rf(ctx, upn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, upn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type Client_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - upn string
func (_e *Client_Expecter) GetUser(ctx interface{}, upn interface{}) *Client_GetUser_Call {
	return &Client_GetUser_Call{Call: _e.mock.On("GetUser", ctx, upn)}
}

func (_c *Client_GetUser_Call) Run(run func(ctx context.Context, upn string)) *Client_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetUser_Call) Return(_a0 *client.User, _a1 error) *Client_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetUser_Call) RunAndReturn(run func(context.Context, string) (*client.User, error)) *Client_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListAIAPIKeys provides a mock function with given fields: ctx, deploymentID
func (_m *Client) ListAIAPIKeys(ctx context.Context, deploymentID string) ([]client.AIAPIKey, error) {
	ret := _m.Called(ctx, deploymentID)

	if len(ret) == 0 {
		panic("no return value specified for ListAIAPIKeys")
	}

	var r0 []client.AIAPIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]client.AIAPIKey, error)); ok {
		return rf(ctx, deploymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []client.AIAPIKey); ok {
		r0 = rf(ctx, deploymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.AIAPIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, deploymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListAIAPIKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAIAPIKeys'
type Client_ListAIAPIKeys_Call struct {
	*mock.Call
}

// ListAIAPIKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID string
func (_e *Client_Expecter) ListAIAPIKeys(ctx interface{}, deploymentID interface{}) *Client_ListAIAPIKeys_Call {
	return &Client_ListAIAPIKeys_Call{Call: _e.mock.On("ListAIAPIKeys", ctx, deploymentID)}
}

func (_c *Client_ListAIAPIKeys_Call) Run(run func(ctx context.Context, deploymentID string)) *Client_ListAIAPIKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_ListAIAPIKeys_Call) Return(_a0 []client.AIAPIKey, _a1 error) *Client_ListAIAPIKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListAIAPIKeys_Call) RunAndReturn(run func(context.Context, string) ([]client.AIAPIKey, error)) *Client_ListAIAPIKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ListAIDeployments provides a mock function with given fields: ctx
func (_m *Client) ListAIDeployments(ctx context.Context) ([]client.AIDeployment, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAIDeployments")
	}

	var r0 []client.AIDeployment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.AIDeployment, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.AIDeployment); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.AIDeployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListAIDeployments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAIDeployments'
type Client_ListAIDeployments_Call struct {
	*mock.Call
}

// ListAIDeployments is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Client_Expecter) ListAIDeployments(ctx interface{}) *Client_ListAIDeployments_Call {
	return &Client_ListAIDeployments_Call{Call: _e.mock.On("ListAIDeployments", ctx)}
}

func (_c *Client_ListAIDeployments_Call) Run(run func(ctx context.Context)) *Client_ListAIDeployments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Client_ListAIDeployments_Call) Return(_a0 []client.AIDeployment, _a1 error) *Client_ListAIDeployments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListAIDeployments_Call) RunAndReturn(run func(context.Context) ([]client.AIDeployment, error)) *Client_ListAIDeployments_Call {
	_c.Call.Return(run)
	return _c
}

// ListAIModels provides a mock function with given fields: ctx
func (_m *Client) ListAIModels(ctx context.Context) ([]client.AIModel, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAIModels")
	}

	var r0 []client.AIModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.AIModel, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.AIModel); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.AIModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListAIModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAIModels'
type Client_ListAIModels_Call struct {
	*mock.Call
}

// ListAIModels is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Client_Expecter) ListAIModels(ctx interface{}) *Client_ListAIModels_Call {
	return &Client_ListAIModels_Call{Call: _e.mock.On("ListAIModels", ctx)}
}

func (_c *Client_ListAIModels_Call) Run(run func(ctx context.Context)) *Client_ListAIModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Client_ListAIModels_Call) Return(_a0 []client.AIModel, _a1 error) *Client_ListAIModels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListAIModels_Call) RunAndReturn(run func(context.Context) ([]client.AIModel, error)) *Client_ListAIModels_Call {
	_c.Call.Return(run)
	return _c
}

// ListClusters provides a mock function with given fields: ctx
func (_m *Client) ListClusters(ctx context.Context) (client.ClusterList, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListClusters")
	}

	var r0 client.ClusterList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (client.ClusterList, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) client.ClusterList); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ClusterList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusters'
type Client_ListClusters_Call struct {
	*mock.Call
}

// ListClusters is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Client_Expecter) ListClusters(ctx interface{}) *Client_ListClusters_Call {
	return &Client_ListClusters_Call{Call: _e.mock.On("ListClusters", ctx)}
}

func (_c *Client_ListClusters_Call) Run(run func(ctx context.Context)) *Client_ListClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Client_ListClusters_Call) Return(_a0 client.ClusterList, _a1 error) *Client_ListClusters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListClusters_Call) RunAndReturn(run func(context.Context) (client.ClusterList, error)) *Client_ListClusters_Call {
	_c.Call.Return(run)
	return _c
}

// ListIntegrationInstances provides a mock function with given fields: ctx
func (_m *Client) ListIntegrationInstances(ctx context.Context) ([]client.IntegrationInstance, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListIntegrationInstances")
	}

	var r0 []client.IntegrationInstance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.IntegrationInstance, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.IntegrationInstance); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.IntegrationInstance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListIntegrationInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIntegrationInstances'
type Client_ListIntegrationInstances_Call struct {
	*mock.Call
}

// ListIntegrationInstances is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Client_Expecter) ListIntegrationInstances(ctx interface{}) *Client_ListIntegrationInstances_Call {
	return &Client_ListIntegrationInstances_Call{Call: _e.mock.On("ListIntegrationInstances", ctx)}
}

func (_c *Client_ListIntegrationInstances_Call) Run(run func(ctx context.Context)) *Client_ListIntegrationInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Client_ListIntegrationInstances_Call) Return(_a0 []client.IntegrationInstance, _a1 error) *Client_ListIntegrationInstances_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListIntegrationInstances_Call) RunAndReturn(run func(context.Context) ([]client.IntegrationInstance, error)) *Client_ListIntegrationInstances_Call {
	_c.Call.Return(run)
	return _c
}

// ListTeams provides a mock function with given fields: ctx
func (_m *Client) ListTeams(ctx context.Context) ([]client.Team, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTeams")
	}

	var r0 []client.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.Team, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.Team); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTeams'
type Client_ListTeams_Call struct {
	*mock.Call
}

// ListTeams is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Client_Expecter) ListTeams(ctx interface{}) *Client_ListTeams_Call {
	return &Client_ListTeams_Call{Call: _e.mock.On("ListTeams", ctx)}
}

func (_c *Client_ListTeams_Call) Run(run func(ctx context.Context)) *Client_ListTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Client_ListTeams_Call) Return(_a0 []client.Team, _a1 error) *Client_ListTeams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListTeams_Call) RunAndReturn(run func(context.Context) ([]client.Team, error)) *Client_ListTeams_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx
func (_m *Client) ListUsers(ctx context.Context) ([]client.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []client.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type Client_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Client_Expecter) ListUsers(ctx interface{}) *Client_ListUsers_Call {
	return &Client_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx)}
}

func (_c *Client_ListUsers_Call) Run(run func(ctx context.Context)) *Client_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Client_ListUsers_Call) Return(_a0 []client.User, _a1 error) *Client_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListUsers_Call) RunAndReturn(run func(context.Context) ([]client.User, error)) *Client_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveClusterMember provides a mock function with given fields: ctx, clusterID, memberID
func (_m *Client) RemoveClusterMember(ctx context.Context, clusterID string, memberID string) error {
	ret := _m.Called(ctx, clusterID, memberID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveClusterMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, clusterID, memberID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_RemoveClusterMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveClusterMember'
type Client_RemoveClusterMember_Call struct {
	*mock.Call
}

// RemoveClusterMember is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
//   - memberID string
func (_e *Client_Expecter) RemoveClusterMember(ctx interface{}, clusterID interface{}, memberID interface{}) *Client_RemoveClusterMember_Call {
	return &Client_RemoveClusterMember_Call{Call: _e.mock.On("RemoveClusterMember", ctx, clusterID, memberID)}
}

func (_c *Client_RemoveClusterMember_Call) Run(run func(ctx context.Context, clusterID string, memberID string)) *Client_RemoveClusterMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Client_RemoveClusterMember_Call) Return(_a0 error) *Client_RemoveClusterMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_RemoveClusterMember_Call) RunAndReturn(run func(context.Context, string, string) error) *Client_RemoveClusterMember_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTeamMember provides a mock function with given fields: ctx, teamID, memberID
func (_m *Client) RemoveTeamMember(ctx context.Context, teamID string, memberID string) error {
	ret := _m.Called(ctx, teamID, memberID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTeamMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, teamID, memberID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_RemoveTeamMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTeamMember'
type Client_RemoveTeamMember_Call struct {
	*mock.Call
}

// RemoveTeamMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - memberID string
func (_e *Client_Expecter) RemoveTeamMember(ctx interface{}, teamID interface{}, memberID interface{}) *Client_RemoveTeamMember_Call {
	return &Client_RemoveTeamMember_Call{Call: _e.mock.On("RemoveTeamMember", ctx, teamID, memberID)}
}

func (_c *Client_RemoveTeamMember_Call) Run(run func(ctx context.Context, teamID string, memberID string)) *Client_RemoveTeamMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Client_RemoveTeamMember_Call) Return(_a0 error) *Client_RemoveTeamMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_RemoveTeamMember_Call) RunAndReturn(run func(context.Context, string, string) error) *Client_RemoveTeamMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
