// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/intility/indev/pkg/client"

	mock "github.com/stretchr/testify/mock"
)

// ClusterClient is an autogenerated mock type for the ClusterClient type
type ClusterClient struct {
	mock.Mock
}

type ClusterClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ClusterClient) EXPECT() *ClusterClient_Expecter {
	return &ClusterClient_Expecter{mock: &_m.Mock}
}

// AddClusterMember provides a mock function with given fields: ctx, clusterID, request
func (_m *ClusterClient) AddClusterMember(ctx context.Context, clusterID string, request []client.AddClusterMemberRequest) error {
	ret := _m.Called(ctx, clusterID, request)

	if len(ret) == 0 {
		panic("no return value specified for AddClusterMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []client.AddClusterMemberRequest) error); ok {
		r0 = rf(ctx, clusterID, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClusterClient_AddClusterMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddClusterMember'
type ClusterClient_AddClusterMember_Call struct {
	*mock.Call
}

// AddClusterMember is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
//   - request []client.AddClusterMemberRequest
func (_e *ClusterClient_Expecter) AddClusterMember(ctx interface{}, clusterID interface{}, request interface{}) *ClusterClient_AddClusterMember_Call {
	return &ClusterClient_AddClusterMember_Call{Call: _e.mock.On("AddClusterMember", ctx, clusterID, request)}
}

func (_c *ClusterClient_AddClusterMember_Call) Run(run func(ctx context.Context, clusterID string, request []client.AddClusterMemberRequest)) *ClusterClient_AddClusterMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]client.AddClusterMemberRequest))
	})
	return _c
}

func (_c *ClusterClient_AddClusterMember_Call) Return(_a0 error) *ClusterClient_AddClusterMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClusterClient_AddClusterMember_Call) RunAndReturn(run func(context.Context, string, []client.AddClusterMemberRequest) error) *ClusterClient_AddClusterMember_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCluster provides a mock function with given fields: ctx, request
func (_m *ClusterClient) CreateCluster(ctx context.Context, request client.NewClusterRequest) (*client.Cluster, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateCluster")
	}

	var r0 *client.Cluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.NewClusterRequest) (*client.Cluster, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.NewClusterRequest) *client.Cluster); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Cluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.NewClusterRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterClient_CreateCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCluster'
type ClusterClient_CreateCluster_Call struct {
	*mock.Call
}

// CreateCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - request client.NewClusterRequest
func (_e *ClusterClient_Expecter) CreateCluster(ctx interface{}, request interface{}) *ClusterClient_CreateCluster_Call {
	return &ClusterClient_CreateCluster_Call{Call: _e.mock.On("CreateCluster", ctx, request)}
}

func (_c *ClusterClient_CreateCluster_Call) Run(run func(ctx context.Context, request client.NewClusterRequest)) *ClusterClient_CreateCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.NewClusterRequest))
	})
	return _c
}

func (_c *ClusterClient_CreateCluster_Call) Return(_a0 *client.Cluster, _a1 error) *ClusterClient_CreateCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClusterClient_CreateCluster_Call) RunAndReturn(run func(context.Context, client.NewClusterRequest) (*client.Cluster, error)) *ClusterClient_CreateCluster_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCluster provides a mock function with given fields: ctx, name
func (_m *ClusterClient) DeleteCluster(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClusterClient_DeleteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCluster'
type ClusterClient_DeleteCluster_Call struct {
	*mock.Call
}

// DeleteCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *ClusterClient_Expecter) DeleteCluster(ctx interface{}, name interface{}) *ClusterClient_DeleteCluster_Call {
	return &ClusterClient_DeleteCluster_Call{Call: _e.mock.On("DeleteCluster", ctx, name)}
}

func (_c *ClusterClient_DeleteCluster_Call) Run(run func(ctx context.Context, name string)) *ClusterClient_DeleteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClusterClient_DeleteCluster_Call) Return(_a0 error) *ClusterClient_DeleteCluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClusterClient_DeleteCluster_Call) RunAndReturn(run func(context.Context, string) error) *ClusterClient_DeleteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// GetCluster provides a mock function with given fields: ctx, name
func (_m *ClusterClient) GetCluster(ctx context.Context, name string) (*client.Cluster, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetCluster")
	}

	var r0 *client.Cluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.Cluster, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.Cluster); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Cluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterClient_GetCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCluster'
type ClusterClient_GetCluster_Call struct {
	*mock.Call
}

// GetCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *ClusterClient_Expecter) GetCluster(ctx interface{}, name interface{}) *ClusterClient_GetCluster_Call {
	return &ClusterClient_GetCluster_Call{Call: _e.mock.On("GetCluster", ctx, name)}
}

func (_c *ClusterClient_GetCluster_Call) Run(run func(ctx context.Context, name string)) *ClusterClient_GetCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClusterClient_GetCluster_Call) Return(_a0 *client.Cluster, _a1 error) *ClusterClient_GetCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClusterClient_GetCluster_Call) RunAndReturn(run func(context.Context, string) (*client.Cluster, error)) *ClusterClient_GetCluster_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterMembers provides a mock function with given fields: ctx, clusterID
func (_m *ClusterClient) GetClusterMembers(ctx context.Context, clusterID string) ([]client.ClusterMember, error) {
	ret := _m.Called(ctx, clusterID)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterMembers")
	}

	var r0 []client.ClusterMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]client.ClusterMember, error)); ok {
		return rf(ctx, clusterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []client.ClusterMember); ok {
		r0 = rf(ctx, clusterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.ClusterMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterClient_GetClusterMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterMembers'
type ClusterClient_GetClusterMembers_Call struct {
	*mock.Call
}

// GetClusterMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
func (_e *ClusterClient_Expecter) GetClusterMembers(ctx interface{}, clusterID interface{}) *ClusterClient_GetClusterMembers_Call {
	return &ClusterClient_GetClusterMembers_Call{Call: _e.mock.On("GetClusterMembers", ctx, clusterID)}
}

func (_c *ClusterClient_GetClusterMembers_Call) Run(run func(ctx context.Context, clusterID string)) *ClusterClient_GetClusterMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClusterClient_GetClusterMembers_Call) Return(_a0 []client.ClusterMember, _a1 error) *ClusterClient_GetClusterMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClusterClient_GetClusterMembers_Call) RunAndReturn(run func(context.Context, string) ([]client.ClusterMember, error)) *ClusterClient_GetClusterMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterStatus provides a mock function with given fields: ctx, clusterID
func (_m *ClusterClient) GetClusterStatus(ctx context.Context, clusterID string) (*client.Cluster, error) {
	ret := _m.Called(ctx, clusterID)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterStatus")
	}

	var r0 *client.Cluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.Cluster, error)); ok {
		return rf(ctx, clusterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.Cluster); ok {
		r0 = rf(ctx, clusterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Cluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterClient_GetClusterStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterStatus'
type ClusterClient_GetClusterStatus_Call struct {
	*mock.Call
}

// GetClusterStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
func (_e *ClusterClient_Expecter) GetClusterStatus(ctx interface{}, clusterID interface{}) *ClusterClient_GetClusterStatus_Call {
	return &ClusterClient_GetClusterStatus_Call{Call: _e.mock.On("GetClusterStatus", ctx, clusterID)}
}

func (_c *ClusterClient_GetClusterStatus_Call) Run(run func(ctx context.Context, clusterID string)) *ClusterClient_GetClusterStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClusterClient_GetClusterStatus_Call) Return(_a0 *client.Cluster, _a1 error) *ClusterClient_GetClusterStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClusterClient_GetClusterStatus_Call) RunAndReturn(run func(context.Context, string) (*client.Cluster, error)) *ClusterClient_GetClusterStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListClusters provides a mock function with given fields: ctx
func (_m *ClusterClient) ListClusters(ctx context.Context) (client.ClusterList, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListClusters")
	}

	var r0 client.ClusterList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (client.ClusterList, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) client.ClusterList); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ClusterList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterClient_ListClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusters'
type ClusterClient_ListClusters_Call struct {
	*mock.Call
}

// ListClusters is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ClusterClient_Expecter) ListClusters(ctx interface{}) *ClusterClient_ListClusters_Call {
	return &ClusterClient_ListClusters_Call{Call: _e.mock.On("ListClusters", ctx)}
}

func (_c *ClusterClient_ListClusters_Call) Run(run func(ctx context.Context)) *ClusterClient_ListClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ClusterClient_ListClusters_Call) Return(_a0 client.ClusterList, _a1 error) *ClusterClient_ListClusters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClusterClient_ListClusters_Call) RunAndReturn(run func(context.Context) (client.ClusterList, error)) *ClusterClient_ListClusters_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveClusterMember provides a mock function with given fields: ctx, clusterID, memberID
func (_m *ClusterClient) RemoveClusterMember(ctx context.Context, clusterID string, memberID string) error {
	ret := _m.Called(ctx, clusterID, memberID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveClusterMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, clusterID, memberID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClusterClient_RemoveClusterMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveClusterMember'
type ClusterClient_RemoveClusterMember_Call struct {
	*mock.Call
}

// RemoveClusterMember is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
//   - memberID string
func (_e *ClusterClient_Expecter) RemoveClusterMember(ctx interface{}, clusterID interface{}, memberID interface{}) *ClusterClient_RemoveClusterMember_Call {
	return &ClusterClient_RemoveClusterMember_Call{Call: _e.mock.On("RemoveClusterMember", ctx, clusterID, memberID)}
}

func (_c *ClusterClient_RemoveClusterMember_Call) Run(run func(ctx context.Context, clusterID string, memberID string)) *ClusterClient_RemoveClusterMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClusterClient_RemoveClusterMember_Call) Return(_a0 error) *ClusterClient_RemoveClusterMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClusterClient_RemoveClusterMember_Call) RunAndReturn(run func(context.Context, string, string) error) *ClusterClient_RemoveClusterMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewClusterClient creates a new instance of ClusterClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClusterClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClusterClient {
	mock := &ClusterClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
