// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/intility/indev/pkg/client"

	mock "github.com/stretchr/testify/mock"
)

// IntegrationClient is an autogenerated mock type for the IntegrationClient type
type IntegrationClient struct {
	mock.Mock
}

type IntegrationClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IntegrationClient) EXPECT() *IntegrationClient_Expecter {
	return &IntegrationClient_Expecter{mock: &_m.Mock}
}

// ListIntegrationInstances provides a mock function with given fields: ctx
func (_m *IntegrationClient) ListIntegrationInstances(ctx context.Context) ([]client.IntegrationInstance, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListIntegrationInstances")
	}

	var r0 []client.IntegrationInstance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.IntegrationInstance, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.IntegrationInstance); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.IntegrationInstance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IntegrationClient_ListIntegrationInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIntegrationInstances'
type IntegrationClient_ListIntegrationInstances_Call struct {
	*mock.Call
}

// ListIntegrationInstances is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IntegrationClient_Expecter) ListIntegrationInstances(ctx interface{}) *IntegrationClient_ListIntegrationInstances_Call {
	return &IntegrationClient_ListIntegrationInstances_Call{Call: _e.mock.On("ListIntegrationInstances", ctx)}
}

func (_c *IntegrationClient_ListIntegrationInstances_Call) Run(run func(ctx context.Context)) *IntegrationClient_ListIntegrationInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IntegrationClient_ListIntegrationInstances_Call) Return(_a0 []client.IntegrationInstance, _a1 error) *IntegrationClient_ListIntegrationInstances_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IntegrationClient_ListIntegrationInstances_Call) RunAndReturn(run func(context.Context) ([]client.IntegrationInstance, error)) *IntegrationClient_ListIntegrationInstances_Call {
	_c.Call.Return(run)
	return _c
}

// NewIntegrationClient creates a new instance of IntegrationClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIntegrationClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IntegrationClient {
	mock := &IntegrationClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
