// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/intility/indev/pkg/client"
	mock "github.com/stretchr/testify/mock"
)

// MeClient is an autogenerated mock type for the MeClient type
type MeClient struct {
	mock.Mock
}

type MeClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MeClient) EXPECT() *MeClient_Expecter {
	return &MeClient_Expecter{mock: &_m.Mock}
}

// GetMe provides a mock function with given fields: ctx
func (_m *MeClient) GetMe(ctx context.Context) (client.Me, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 client.Me
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (client.Me, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) client.Me); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(client.Me)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MeClient_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type MeClient_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MeClient_Expecter) GetMe(ctx interface{}) *MeClient_GetMe_Call {
	return &MeClient_GetMe_Call{Call: _e.mock.On("GetMe", ctx)}
}

func (_c *MeClient_GetMe_Call) Run(run func(ctx context.Context)) *MeClient_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MeClient_GetMe_Call) Return(_a0 client.Me, _a1 error) *MeClient_GetMe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MeClient_GetMe_Call) RunAndReturn(run func(context.Context) (client.Me, error)) *MeClient_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMeClient creates a new instance of MeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MeClient {
	mock := &MeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
