// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/intility/indev/pkg/client"

	mock "github.com/stretchr/testify/mock"
)

// MemberClient is an autogenerated mock type for the MemberClient type
type MemberClient struct {
	mock.Mock
}

type MemberClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MemberClient) EXPECT() *MemberClient_Expecter {
	return &MemberClient_Expecter{mock: &_m.Mock}
}

// AddTeamMember provides a mock function with given fields: ctx, teamID, request
func (_m *MemberClient) AddTeamMember(ctx context.Context, teamID string, request []client.AddTeamMemberRequest) error {
	ret := _m.Called(ctx, teamID, request)

	if len(ret) == 0 {
		panic("no return value specified for AddTeamMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []client.AddTeamMemberRequest) error); ok {
		r0 = rf(ctx, teamID, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MemberClient_AddTeamMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTeamMember'
type MemberClient_AddTeamMember_Call struct {
	*mock.Call
}

// AddTeamMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - request []client.AddTeamMemberRequest
func (_e *MemberClient_Expecter) AddTeamMember(ctx interface{}, teamID interface{}, request interface{}) *MemberClient_AddTeamMember_Call {
	return &MemberClient_AddTeamMember_Call{Call: _e.mock.On("AddTeamMember", ctx, teamID, request)}
}

func (_c *MemberClient_AddTeamMember_Call) Run(run func(ctx context.Context, teamID string, request []client.AddTeamMemberRequest)) *MemberClient_AddTeamMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]client.AddTeamMemberRequest))
	})
	return _c
}

func (_c *MemberClient_AddTeamMember_Call) Return(_a0 error) *MemberClient_AddTeamMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberClient_AddTeamMember_Call) RunAndReturn(run func(context.Context, string, []client.AddTeamMemberRequest) error) *MemberClient_AddTeamMember_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTeamMember provides a mock function with given fields: ctx, teamID, memberID
func (_m *MemberClient) RemoveTeamMember(ctx context.Context, teamID string, memberID string) error {
	ret := _m.Called(ctx, teamID, memberID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTeamMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, teamID, memberID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MemberClient_RemoveTeamMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTeamMember'
type MemberClient_RemoveTeamMember_Call struct {
	*mock.Call
}

// RemoveTeamMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - memberID string
func (_e *MemberClient_Expecter) RemoveTeamMember(ctx interface{}, teamID interface{}, memberID interface{}) *MemberClient_RemoveTeamMember_Call {
	return &MemberClient_RemoveTeamMember_Call{Call: _e.mock.On("RemoveTeamMember", ctx, teamID, memberID)}
}

func (_c *MemberClient_RemoveTeamMember_Call) Run(run func(ctx context.Context, teamID string, memberID string)) *MemberClient_RemoveTeamMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MemberClient_RemoveTeamMember_Call) Return(_a0 error) *MemberClient_RemoveTeamMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberClient_RemoveTeamMember_Call) RunAndReturn(run func(context.Context, string, string) error) *MemberClient_RemoveTeamMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMemberClient creates a new instance of MemberClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberClient {
	mock := &MemberClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
