// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/intility/indev/pkg/client"

	mock "github.com/stretchr/testify/mock"
)

// PullSecretClient is an autogenerated mock type for the PullSecretClient type
type PullSecretClient struct {
	mock.Mock
}

type PullSecretClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PullSecretClient) EXPECT() *PullSecretClient_Expecter {
	return &PullSecretClient_Expecter{mock: &_m.Mock}
}

// CreatePullSecret provides a mock function with given fields: ctx, request
func (_m *PullSecretClient) CreatePullSecret(ctx context.Context, request client.NewPullSecretRequest) (*client.PullSecret, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullSecret")
	}

	var r0 *client.PullSecret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.NewPullSecretRequest) (*client.PullSecret, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.NewPullSecretRequest) *client.PullSecret); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PullSecret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.NewPullSecretRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullSecretClient_CreatePullSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullSecret'
type PullSecretClient_CreatePullSecret_Call struct {
	*mock.Call
}

// CreatePullSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - request client.NewPullSecretRequest
func (_e *PullSecretClient_Expecter) CreatePullSecret(ctx interface{}, request interface{}) *PullSecretClient_CreatePullSecret_Call {
	return &PullSecretClient_CreatePullSecret_Call{Call: _e.mock.On("CreatePullSecret", ctx, request)}
}

func (_c *PullSecretClient_CreatePullSecret_Call) Run(run func(ctx context.Context, request client.NewPullSecretRequest)) *PullSecretClient_CreatePullSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.NewPullSecretRequest))
	})
	return _c
}

func (_c *PullSecretClient_CreatePullSecret_Call) Return(_a0 *client.PullSecret, _a1 error) *PullSecretClient_CreatePullSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullSecretClient_CreatePullSecret_Call) RunAndReturn(run func(context.Context, client.NewPullSecretRequest) (*client.PullSecret, error)) *PullSecretClient_CreatePullSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePullSecret provides a mock function with given fields: ctx, id
func (_m *PullSecretClient) DeletePullSecret(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePullSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PullSecretClient_DeletePullSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePullSecret'
type PullSecretClient_DeletePullSecret_Call struct {
	*mock.Call
}

// DeletePullSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PullSecretClient_Expecter) DeletePullSecret(ctx interface{}, id interface{}) *PullSecretClient_DeletePullSecret_Call {
	return &PullSecretClient_DeletePullSecret_Call{Call: _e.mock.On("DeletePullSecret", ctx, id)}
}

func (_c *PullSecretClient_DeletePullSecret_Call) Run(run func(ctx context.Context, id string)) *PullSecretClient_DeletePullSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PullSecretClient_DeletePullSecret_Call) Return(_a0 error) *PullSecretClient_DeletePullSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PullSecretClient_DeletePullSecret_Call) RunAndReturn(run func(context.Context, string) error) *PullSecretClient_DeletePullSecret_Call {
	_c.Call.Return(run)
	return _c
}

// EditPullSecret provides a mock function with given fields: ctx, id, request
func (_m *PullSecretClient) EditPullSecret(ctx context.Context, id string, request client.EditPullSecretRequest) (*client.PullSecret, error) {
	ret := _m.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for EditPullSecret")
	}

	var r0 *client.PullSecret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, client.EditPullSecretRequest) (*client.PullSecret, error)); ok {
		return rf(ctx, id, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, client.EditPullSecretRequest) *client.PullSecret); ok {
		r0 = rf(ctx, id, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PullSecret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, client.EditPullSecretRequest) error); ok {
		r1 = rf(ctx, id, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullSecretClient_EditPullSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditPullSecret'
type PullSecretClient_EditPullSecret_Call struct {
	*mock.Call
}

// EditPullSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - request client.EditPullSecretRequest
func (_e *PullSecretClient_Expecter) EditPullSecret(ctx interface{}, id interface{}, request interface{}) *PullSecretClient_EditPullSecret_Call {
	return &PullSecretClient_EditPullSecret_Call{Call: _e.mock.On("EditPullSecret", ctx, id, request)}
}

func (_c *PullSecretClient_EditPullSecret_Call) Run(run func(ctx context.Context, id string, request client.EditPullSecretRequest)) *PullSecretClient_EditPullSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(client.EditPullSecretRequest))
	})
	return _c
}

func (_c *PullSecretClient_EditPullSecret_Call) Return(_a0 *client.PullSecret, _a1 error) *PullSecretClient_EditPullSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullSecretClient_EditPullSecret_Call) RunAndReturn(run func(context.Context, string, client.EditPullSecretRequest) (*client.PullSecret, error)) *PullSecretClient_EditPullSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetPullSecret provides a mock function with given fields: ctx, id
func (_m *PullSecretClient) GetPullSecret(ctx context.Context, id string) (*client.PullSecret, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPullSecret")
	}

	var r0 *client.PullSecret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.PullSecret, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.PullSecret); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PullSecret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullSecretClient_GetPullSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPullSecret'
type PullSecretClient_GetPullSecret_Call struct {
	*mock.Call
}

// GetPullSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PullSecretClient_Expecter) GetPullSecret(ctx interface{}, id interface{}) *PullSecretClient_GetPullSecret_Call {
	return &PullSecretClient_GetPullSecret_Call{Call: _e.mock.On("GetPullSecret", ctx, id)}
}

func (_c *PullSecretClient_GetPullSecret_Call) Run(run func(ctx context.Context, id string)) *PullSecretClient_GetPullSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PullSecretClient_GetPullSecret_Call) Return(_a0 *client.PullSecret, _a1 error) *PullSecretClient_GetPullSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullSecretClient_GetPullSecret_Call) RunAndReturn(run func(context.Context, string) (*client.PullSecret, error)) *PullSecretClient_GetPullSecret_Call {
	_c.Call.Return(run)
	return _c
}

// ListPullSecrets provides a mock function with given fields: ctx
func (_m *PullSecretClient) ListPullSecrets(ctx context.Context) ([]client.PullSecret, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPullSecrets")
	}

	var r0 []client.PullSecret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.PullSecret, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.PullSecret); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.PullSecret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullSecretClient_ListPullSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPullSecrets'
type PullSecretClient_ListPullSecrets_Call struct {
	*mock.Call
}

// ListPullSecrets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PullSecretClient_Expecter) ListPullSecrets(ctx interface{}) *PullSecretClient_ListPullSecrets_Call {
	return &PullSecretClient_ListPullSecrets_Call{Call: _e.mock.On("ListPullSecrets", ctx)}
}

func (_c *PullSecretClient_ListPullSecrets_Call) Run(run func(ctx context.Context)) *PullSecretClient_ListPullSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PullSecretClient_ListPullSecrets_Call) Return(_a0 []client.PullSecret, _a1 error) *PullSecretClient_ListPullSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullSecretClient_ListPullSecrets_Call) RunAndReturn(run func(context.Context) ([]client.PullSecret, error)) *PullSecretClient_ListPullSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// SetClusterPullSecret provides a mock function with given fields: ctx, clusterID, pullSecretID
func (_m *PullSecretClient) SetClusterPullSecret(ctx context.Context, clusterID string, pullSecretID string) error {
	ret := _m.Called(ctx, clusterID, pullSecretID)

	if len(ret) == 0 {
		panic("no return value specified for SetClusterPullSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, clusterID, pullSecretID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PullSecretClient_SetClusterPullSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetClusterPullSecret'
type PullSecretClient_SetClusterPullSecret_Call struct {
	*mock.Call
}

// SetClusterPullSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
//   - pullSecretID string
func (_e *PullSecretClient_Expecter) SetClusterPullSecret(ctx interface{}, clusterID interface{}, pullSecretID interface{}) *PullSecretClient_SetClusterPullSecret_Call {
	return &PullSecretClient_SetClusterPullSecret_Call{Call: _e.mock.On("SetClusterPullSecret", ctx, clusterID, pullSecretID)}
}

func (_c *PullSecretClient_SetClusterPullSecret_Call) Run(run func(ctx context.Context, clusterID string, pullSecretID string)) *PullSecretClient_SetClusterPullSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *PullSecretClient_SetClusterPullSecret_Call) Return(_a0 error) *PullSecretClient_SetClusterPullSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PullSecretClient_SetClusterPullSecret_Call) RunAndReturn(run func(context.Context, string, string) error) *PullSecretClient_SetClusterPullSecret_Call {
	_c.Call.Return(run)
	return _c
}

// NewPullSecretClient creates a new instance of PullSecretClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullSecretClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullSecretClient {
	mock := &PullSecretClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
