// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	client "github.com/intility/indev/pkg/client"
	mock "github.com/stretchr/testify/mock"
)

// RestClientOption is an autogenerated mock type for the RestClientOption type
type RestClientOption struct {
	mock.Mock
}

type RestClientOption_Expecter struct {
	mock *mock.Mock
}

func (_m *RestClientOption) EXPECT() *RestClientOption_Expecter {
	return &RestClientOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *RestClientOption) Execute(_a0 *client.RestClient) {
	_m.Called(_a0)
}

// RestClientOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type RestClientOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *client.RestClient
func (_e *RestClientOption_Expecter) Execute(_a0 interface{}) *RestClientOption_Execute_Call {
	return &RestClientOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *RestClientOption_Execute_Call) Run(run func(_a0 *client.RestClient)) *RestClientOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*client.RestClient))
	})
	return _c
}

func (_c *RestClientOption_Execute_Call) Return() *RestClientOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *RestClientOption_Execute_Call) RunAndReturn(run func(*client.RestClient)) *RestClientOption_Execute_Call {
	_c.Run(run)
	return _c
}

// NewRestClientOption creates a new instance of RestClientOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRestClientOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *RestClientOption {
	mock := &RestClientOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
