// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/intility/indev/pkg/client"

	mock "github.com/stretchr/testify/mock"
)

// TeamsClient is an autogenerated mock type for the TeamsClient type
type TeamsClient struct {
	mock.Mock
}

type TeamsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamsClient) EXPECT() *TeamsClient_Expecter {
	return &TeamsClient_Expecter{mock: &_m.Mock}
}

// CreateTeam provides a mock function with given fields: ctx, request
func (_m *TeamsClient) CreateTeam(ctx context.Context, request client.NewTeamRequest) (*client.Team, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 *client.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.NewTeamRequest) (*client.Team, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.NewTeamRequest) *client.Team); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.NewTeamRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamsClient_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type TeamsClient_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - request client.NewTeamRequest
func (_e *TeamsClient_Expecter) CreateTeam(ctx interface{}, request interface{}) *TeamsClient_CreateTeam_Call {
	return &TeamsClient_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, request)}
}

func (_c *TeamsClient_CreateTeam_Call) Run(run func(ctx context.Context, request client.NewTeamRequest)) *TeamsClient_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.NewTeamRequest))
	})
	return _c
}

func (_c *TeamsClient_CreateTeam_Call) Return(_a0 *client.Team, _a1 error) *TeamsClient_CreateTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamsClient_CreateTeam_Call) RunAndReturn(run func(context.Context, client.NewTeamRequest) (*client.Team, error)) *TeamsClient_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTeam provides a mock function with given fields: ctx, request
func (_m *TeamsClient) DeleteTeam(ctx context.Context, request client.DeleteTeamRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.DeleteTeamRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeamsClient_DeleteTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTeam'
type TeamsClient_DeleteTeam_Call struct {
	*mock.Call
}

// DeleteTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - request client.DeleteTeamRequest
func (_e *TeamsClient_Expecter) DeleteTeam(ctx interface{}, request interface{}) *TeamsClient_DeleteTeam_Call {
	return &TeamsClient_DeleteTeam_Call{Call: _e.mock.On("DeleteTeam", ctx, request)}
}

func (_c *TeamsClient_DeleteTeam_Call) Run(run func(ctx context.Context, request client.DeleteTeamRequest)) *TeamsClient_DeleteTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.DeleteTeamRequest))
	})
	return _c
}

func (_c *TeamsClient_DeleteTeam_Call) Return(_a0 error) *TeamsClient_DeleteTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeamsClient_DeleteTeam_Call) RunAndReturn(run func(context.Context, client.DeleteTeamRequest) error) *TeamsClient_DeleteTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function with given fields: ctx, name
func (_m *TeamsClient) GetTeam(ctx context.Context, name string) (*client.Team, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *client.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.Team, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.Team); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamsClient_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type TeamsClient_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *TeamsClient_Expecter) GetTeam(ctx interface{}, name interface{}) *TeamsClient_GetTeam_Call {
	return &TeamsClient_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, name)}
}

func (_c *TeamsClient_GetTeam_Call) Run(run func(ctx context.Context, name string)) *TeamsClient_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TeamsClient_GetTeam_Call) Return(_a0 *client.Team, _a1 error) *TeamsClient_GetTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamsClient_GetTeam_Call) RunAndReturn(run func(context.Context, string) (*client.Team, error)) *TeamsClient_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamMembers provides a mock function with given fields: ctx, teamID
func (_m *TeamsClient) GetTeamMembers(ctx context.Context, teamID string) ([]client.TeamMember, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamMembers")
	}

	var r0 []client.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]client.TeamMember, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []client.TeamMember); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamsClient_GetTeamMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamMembers'
type TeamsClient_GetTeamMembers_Call struct {
	*mock.Call
}

// GetTeamMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *TeamsClient_Expecter) GetTeamMembers(ctx interface{}, teamID interface{}) *TeamsClient_GetTeamMembers_Call {
	return &TeamsClient_GetTeamMembers_Call{Call: _e.mock.On("GetTeamMembers", ctx, teamID)}
}

func (_c *TeamsClient_GetTeamMembers_Call) Run(run func(ctx context.Context, teamID string)) *TeamsClient_GetTeamMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TeamsClient_GetTeamMembers_Call) Return(_a0 []client.TeamMember, _a1 error) *TeamsClient_GetTeamMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamsClient_GetTeamMembers_Call) RunAndReturn(run func(context.Context, string) ([]client.TeamMember, error)) *TeamsClient_GetTeamMembers_Call {
	_c.Call.Return(run)
	return _c
}

// ListTeams provides a mock function with given fields: ctx
func (_m *TeamsClient) ListTeams(ctx context.Context) ([]client.Team, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTeams")
	}

	var r0 []client.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.Team, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.Team); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamsClient_ListTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTeams'
type TeamsClient_ListTeams_Call struct {
	*mock.Call
}

// ListTeams is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TeamsClient_Expecter) ListTeams(ctx interface{}) *TeamsClient_ListTeams_Call {
	return &TeamsClient_ListTeams_Call{Call: _e.mock.On("ListTeams", ctx)}
}

func (_c *TeamsClient_ListTeams_Call) Run(run func(ctx context.Context)) *TeamsClient_ListTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TeamsClient_ListTeams_Call) Return(_a0 []client.Team, _a1 error) *TeamsClient_ListTeams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamsClient_ListTeams_Call) RunAndReturn(run func(context.Context) ([]client.Team, error)) *TeamsClient_ListTeams_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamsClient creates a new instance of TeamsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamsClient {
	mock := &TeamsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
