// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/intility/indev/pkg/client"
	mock "github.com/stretchr/testify/mock"
)

// UserClient is an autogenerated mock type for the UserClient type
type UserClient struct {
	mock.Mock
}

type UserClient_Expecter struct {
	mock *mock.Mock
}

func (_m *UserClient) EXPECT() *UserClient_Expecter {
	return &UserClient_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function with given fields: ctx, upn
func (_m *UserClient) GetUser(ctx context.Context, upn string) (*client.User, error) {
	ret := _m.Called(ctx, upn)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *client.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.User, error)); ok {
		return rf(ctx, upn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.User); ok {
		r0 = rf(ctx, upn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, upn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserClient_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserClient_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - upn string
func (_e *UserClient_Expecter) GetUser(ctx interface{}, upn interface{}) *UserClient_GetUser_Call {
	return &UserClient_GetUser_Call{Call: _e.mock.On("GetUser", ctx, upn)}
}

func (_c *UserClient_GetUser_Call) Run(run func(ctx context.Context, upn string)) *UserClient_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserClient_GetUser_Call) Return(_a0 *client.User, _a1 error) *UserClient_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserClient_GetUser_Call) RunAndReturn(run func(context.Context, string) (*client.User, error)) *UserClient_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx
func (_m *UserClient) ListUsers(ctx context.Context) ([]client.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []client.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserClient_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type UserClient_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserClient_Expecter) ListUsers(ctx interface{}) *UserClient_ListUsers_Call {
	return &UserClient_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx)}
}

func (_c *UserClient_ListUsers_Call) Run(run func(ctx context.Context)) *UserClient_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserClient_ListUsers_Call) Return(_a0 []client.User, _a1 error) *UserClient_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserClient_ListUsers_Call) RunAndReturn(run func(context.Context) ([]client.User, error)) *UserClient_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserClient creates a new instance of UserClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserClient {
	mock := &UserClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
