# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build, test, release

on:
  release:
    types: [published]
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -o bin/indev cmd/indev/main.go

    - name: Test
      run: go test ./...

    - name: GoReleaser Action
      uses: goreleaser/goreleaser-action@v5.1.0
      with:
        args: release --clean --snapshot
        version: 2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAP_REPO_GITHUB_TOKEN: ${{ secrets.TAP_REPO_GITHUB_TOKEN }}
        DOWNLOADER_GITHUB_TOKEN: ${{ secrets.DOWNLOADER_GITHUB_TOKEN }}
        OTLP_ENDPOINT: ${{ vars.OTLP_ENDPOINT }}
        OTLP_TOKEN: ${{ vars.OTLP_TOKEN }}
        SENTRY_DSN: ${{ vars.SENTRY_DSN }}
        AUTH_AUDIENCE: ${{ vars.AUTH_AUDIENCE }}
        AUTH_AUTHORITY: ${{ vars.AUTH_AUTHORITY }}
        AUTH_CLIENT_ID: ${{ vars.AUTH_CLIENT_ID }}
        AUTH_REDIRECT_URI: ${{ vars.AUTH_REDIRECT_URI }}
        PLATFORM_BASE_URI: ${{ vars.PLATFORM_BASE_URI }}
